steps:
# Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/wedlyapp', '.']

# Push the Docker image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/wedlyapp']

# Deploy to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: 
  - 'run'
  - 'deploy'
  - 'wedlyapp'
  - '--image'
  - 'gcr.io/$PROJECT_ID/wedlyapp'
  - '--platform'
  - 'managed'
  - '--region'
  - 'me-central1'
  - '--allow-unauthenticated'
  - '--port'
  - '8080'
  - '--set-env-vars'
  - 'PORT=8080'
  - '--memory'
  - '4Gi'
  - '--cpu'
  - '4'
  - '--max-instances'
  - '10'
  - '--timeout'
  - '900'
  - '--concurrency'
  - '80'
  - '--set-env-vars'
  - 'DEBUG=False,SECRET_KEY=your-secret-key-here,ALLOWED_HOSTS=wedly-app-258355634687.me-central1.run.app,PORT=8080,DJANGO_SETTINGS_MODULE=wedding_project.settings'

images:
- 'gcr.io/$PROJECT_ID/wedlyapp'
