steps:
# Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/wedlyapp', '.']

# Push the Docker image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/wedlyapp']

# Deploy to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: 
  - 'run'
  - 'deploy'
  - 'wedlyapp'
  - '--image'
  - 'gcr.io/$PROJECT_ID/wedlyapp'
  - '--platform'
  - 'managed'
  - '--region'
  - 'us-central1'
  - '--allow-unauthenticated'
  - '--port'
  - '8080'
  - '--memory'
  - '1Gi'
  - '--cpu'
  - '1'
  - '--max-instances'
  - '10'

images:
- 'gcr.io/$PROJECT_ID/wedlyapp'
