version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:8080"
    volumes:
      - ./media:/app/media
      - ./static:/app/static
    environment:
      - DEBUG=False
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=postgresql://wedlyapp:wedlyapp123@db:5432/wedlyapp
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - FIRESTORE_ENABLED=${FIRESTORE_ENABLED:-false}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_CREDENTIALS_JSON=${FIREBASE_CREDENTIALS_JSON}
    depends_on:
      - db
      - redis
    restart: unless-stopped
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn wedding_project.wsgi:application --bind 0.0.0.0:8080 --workers 3"

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=wedlyapp
      - POSTGRES_USER=wedlyapp
      - POSTGRES_PASSWORD=wedlyapp123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/app/static
      - ./media:/app/media
    depends_on:
      - web
    restart: unless-stopped

volumes:
  postgres_data:
