version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./media:/app/media
      - ./static:/app/static
    environment:
      - DEBUG=False
      - SECRET_KEY=django-insecure-=om$f*08=)8i=gmqzud!ql@k=)bsknx-bct32^v^(=qn0vad@l
      - DATABASE_URL=postgresql://postgres.kbdloigsvdrxqngrflvb:Wedly%40%402025@aws-1-us-east-2.pooler.supabase.com:5432/postgres
      - ALLOWED_HOSTS=wedly-app-258355634687.me-central1.run.app,localhost,127.0.0.1,0.0.0.0
    depends_on:
      #- db
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=wedlyapp
      - POSTGRES_USER=wedlyapp
      - POSTGRES_PASSWORD=wedlyapp123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data:
