# Generated by Django 5.2.7 on 2025-10-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="business_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("HALL", "Wedding Hall"),
                    ("MAKEUP", "Makeup Artist"),
                    ("ATELIER", "Atelier"),
                    ("PHOTOGRAPHY", "Photography & Video"),
                    ("SUIT", "Suit Rental"),
                    ("DECOR", "Decoration & Design"),
                    ("MUSIC", "Music & Entertainment"),
                    ("CARS", "Wedding Cars"),
                    ("CATERING", "Catering & Hospitality"),
                    ("VIDEO", "Video Production"),
                    ("NONE", "None"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
