# Generated by Django 5.2.7 on 2025-10-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="profiles/"),
        ),
        migrations.AlterField(
            model_name="user",
            name="business_type",
            field=models.CharField(
                choices=[
                    ("HALL", "Wedding Hall"),
                    ("MAKEUP", "Makeup Artist"),
                    ("ATELIER", "Atelier"),
                    ("PHOTOGRAPHY", "Photography & Video"),
                    ("SUIT", "Suit Rental"),
                    ("DECOR", "Decoration & Design"),
                    ("MUSIC", "Music & Entertainment"),
                    ("CARS", "Wedding Cars"),
                    ("CATERING", "Catering & Hospitality"),
                    ("VIDEO", "Video Production"),
                    ("NONE", "None"),
                ],
                default="NONE",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("OWNER", "Venue Owner"),
                    ("SERVICE", "Service Provider"),
                    ("USER", "Customer"),
                ],
                default="USER",
                max_length=10,
            ),
        ),
    ]
