# Generated by Django 5.2.7 on 2025-10-18 00:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("halls", "0002_remove_installmentpayment_booking_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="venue",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
    ]
